import { useState } from 'react';
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link';
import {
  ApolloClient,
  InMemoryCache,
  gql
} from "@apollo/client";

import Layout from '@components/Layout';
import Container from '@components/Container';
import Button from '@components/Button';

import products from '@data/products';

import styles from '@styles/Home.module.scss'

export default function Home({ page, products }) {
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Container>
        <h1 className="sr-only">Space Jelly Gear</h1>

        <div className={styles.hero}>
          <Link href={page.heroLink}>
            <a>
              <div className={styles.heroContent}>
                <h2>{ page.heroTitle }</h2>
                <p>{ page.heroText }</p>
              </div>
              <Image width={page.heroBackground.width} height={page.heroBackground.height} src={page.heroBackground.url} alt="" />
            </a>
          </Link>
        </div>

        <h2>Featured Gear</h2>

        <ul className={styles.products}>
          {products.map(product => {
            const { images } = product;
            return (
              <li key={product.id}>
                <Link href={`/products/${product.slug}`}>
                  <a>
                    <div className={styles.productImage}>
                      <Image width={images[0].width} height={images[0].height} src={images[0].url} alt="" />
                    </div>
                    <h3 className={styles.productTitle}>
                      { product.name }
                    </h3>
                    <p className={styles.productPrice}>
                      ${ product.price }
                    </p>
                  </a>
                </Link>
                <p>
                  <Button>
                    Add to Cart
                  </Button>
                </p>
              </li>
            )
          })}
        </ul>
      </Container>
    </Layout>
  )
}

export async function getStaticProps({ locale }) {
  const client = new ApolloClient({
    uri: process.env.GRAPHCMS_ENDPOINT,
    cache: new InMemoryCache()
  });

  const { data } = await client.query({
    query: gql`
      query Home($locale: Locale!) {
        page(where: {slug: "home"}) {
          id
          heroLink
          heroText
          heroTitle
          heroBackground {
            url
            width
            height
          }
          localizations(locales: [$locale]) {
            heroText
            heroTitle
          }
        }
        products {
          name
          id
          images {
            id
            url
            width
            height
          }
          price
          slug
        }
      }
    `,
    variables: {
      locale
    }
  })

  const { products } = data;

  let page = data.page;

  if ( page.localizations.length > 0 ) {
    page = {
      ...page,
      ...page.localizations[0]
    }
  }

  return {
    props: {
      page,
      products
    }
  }
}