import { useState } from 'react';
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link';
import {
  ApolloClient,
  InMemoryCache,
  gql
} from "@apollo/client";

import Layout from '@components/Layout';
import Container from '@components/Container';
import Button from '@components/Button';

import products from '@data/products';

import styles from '@styles/Home.module.scss'

export default function Home({ storeLocations }) {
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Container>
        <h1>Find a Store</h1>

        <h2>Locations</h2>

        <ul>
          {storeLocations.map(location => {
            return (
              <li key={location.id}>
                {location.name}
              </li>
            )
          })}
        </ul>
      </Container>
    </Layout>
  )
}

export async function getStaticProps() {
  const client = new ApolloClient({
    uri: process.env.GRAPHCMS_ENDPOINT,
    cache: new InMemoryCache()
  });

  const { data } = await client.query({
    query: gql`
      query Stores {
        storeLocations {
          name
          id
          location {
            longitude
            latitude
          }
        }
      }
    `
  })

  const { storeLocations } = data;

  return {
    props: {
      storeLocations
    }
  }
}